import pytest
from selenium import webdriver
import time


@pytest.fixture
def driver(request):
    wd = webdriver.Firefox(firefox_binary="C:\\Program Files\\Mozilla Firefox\\firefox.exe")
    print(wd.capabilities)
    request.addfinalizer(wd.quit)
    return wd


def test_searching_for_elements_in_admin_menu(driver):
    driver.get("http://localhost/litecart/admin/login.php")
    time.sleep(2)
    driver.find_element_by_name("username").send_keys("admin")
    driver.find_element_by_name("password").send_keys("admin")
    driver.find_element_by_css_selector(".btn.btn-default").click()
    time.sleep(2)
    driver.find_element_by_css_selector("#app-appearance > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-template > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-logotype > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_id("app-catalog").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-catalog > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-product_groups > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-option_groups > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-manufacturers > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-suppliers > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-delivery_statuses > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-sold_out_statuses > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-quantity_units > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-csv > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-countries > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-currencies > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-customers > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-customers > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-csv > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-newsletter > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-geo_zones > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-languages > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-storage_encoding > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-modules > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-customer > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-shipping > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-payment > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-order > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-order_total > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-jobs > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-orders > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-orders > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-order_statuses > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-pages > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-pages > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-csv > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-reports > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-monthly_sales > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-most_sold_products > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-most_shopping_customers > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-settings > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-store_info > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-defaults > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-email > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-listings > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-images > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-checkout > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-advanced > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-security > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-slides > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-tax > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-tax_rates > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-tax_classes > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-translations > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-search > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-scan > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#doc-csv > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-users > a").click()
    driver.find_element_by_tag_name("h1")
    driver.find_element_by_css_selector("#app-vqmods > a").click()
    driver.find_element_by_tag_name("h1")
